# Generated by Django 3.1.5 on 2021-03-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcos',
            name='nom_barco',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='barcos',
            name='num_amarre',
            field=models.IntegerField(unique=True),
        ),
    ]
