# Generated by Django 3.1.5 on 2021-03-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socios',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
