# Generated by Django 3.1.5 on 2021-03-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios_app', '0002_auto_20210316_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='direccion',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='socios',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='socios',
            name='telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
