# Generated by Django 3.1.5 on 2021-03-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios_app', '0003_auto_20210316_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='telefono',
            field=models.IntegerField(unique=True),
        ),
    ]
