# Generated by Django 3.1.5 on 2021-03-19 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barcos_app', '0002_auto_20210318_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='salidas_barcos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('num_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcos_app.barcos')),
            ],
        ),
    ]
