# Generated by Django 3.1.5 on 2021-03-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcos_app', '0002_auto_20210318_1759'),
        ('salidas_barcos_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='salidas_barcos',
            new_name='SalidasBarcos',
        ),
    ]
