# Generated by Django 3.1.5 on 2021-03-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_barcos_app', '0002_auto_20210319_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidasbarcos',
            old_name='num_matricula',
            new_name='id_barco',
        ),
    ]
