# Generated by Django 3.1.5 on 2021-03-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_barcos_app', '0003_auto_20210320_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidasbarcos',
            name='hora',
        ),
        migrations.AlterField(
            model_name='salidasbarcos',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
