# Generated by Django 3.1.5 on 2021-03-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_barcos_app', '0005_auto_20210320_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidasbarcos',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
