# Generated by Django 3.1.5 on 2021-03-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_barcos_app', '0007_auto_20210320_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidasbarcos',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
