# Generated by Django 3.1.5 on 2021-03-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_barcos_app', '0009_salidasbarcos_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidasbarcos',
            old_name='hora',
            new_name='horaa',
        ),
    ]
