# Generated by Django 3.1.5 on 2021-03-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_barcos_app', '0010_auto_20210320_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidasbarcos',
            name='horaa',
        ),
    ]
