# Generated by Django 3.1.5 on 2021-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_barcos_app', '0011_remove_salidasbarcos_horaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidasbarcos',
            name='hora',
            field=models.TimeField(auto_now_add=True, default='06:00:00.000000-08:00'),
            preserve_default=False,
        ),
    ]
